version: '3.8'
services:
  pleo-antaeus:
    build: .
    depends_on:
      - rabbitmq
      - scheduler
    expose:
      - 7000
    image: pleo-antaeus
    ports:
      - 7000:7000
    stdin_open: true
    tty: true
    volumes:
      - pleo-antaeus-build-cache:/root/.gradle

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  scheduler:
    image: lecovi/curl-cron
    environment:
      URL: pleo-antaeus:7000/rest/v1/billing
      CRON_SCHEDULE: "0 3 1 * *"

volumes:
  pleo-antaeus-build-cache: